# Define user
type User {
  _id: ID
  username: String! @unique
  email: String! @unique
  password: String!
  avatar: String
  joinDate: String
  favorites: [Post]
}

# Define post
type Post {
  _id: ID
  title: String!
  imageUrl: String!
  categories: [String]!
  description: String!
  createdDate: String
  likes: Int
  createdBy: User!
  messages: [Message]
}

# Define message
type Message {
  _id: ID
  messageBody: String!
  messageDate: String
  messageUser: User!
}

# Define auth type
type AuthCredentials {
  token: String!,
  userId: ID!
}

# Define infinite posts scroll type
type PostsPage {
  posts: [Post]
  hasMore: Boolean
}

# Define likes and favorites
type LikesFaves {
  likes: Int
  favorites: [Post]
}

# Define queries
type Query {
  getCurrentUser: User
  getPosts: [Post]!
  getUserPosts(userId: ID!): [Post]
  getPost(postId: ID!): Post!
  searchPosts(searchTerm: String): [Post]
  infiniteScrollPosts(pageNum: Int!, pageSize: Int!): PostsPage
}

# Define mutations
type Mutation {
  addPost(
    title: String!
    imageUrl: String!
    categories: [String]!
    description: String!
    creatorId: ID!
  ): Post!
  registerUser(username: String!, email: String!, password: String!): AuthCredentials!
  loginUser(username: String!, password: String!): AuthCredentials!
  addPostComment(commentBody: String!, postId: ID!, userId: ID!): Message!
  likePost(postId: ID!, username: String!): LikesFaves!
  unlikePost(postId: ID!, username: String!): LikesFaves!
}
